/*
 * This source file was generated by the Gradle 'init' task
 */
package team13.tetris;

import org.junit.jupiter.api.Test;

import team13.tetris.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    //@Test void appHasAGreeting() {
    //    App classUnderTest = new App();
    //    assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    //}
}
